# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1241, 690)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1241, 691))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 54, 12))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 54, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 54, 12))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(30, 290, 54, 12))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(30, 350, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(30, 410, 54, 12))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 80, 131, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 130, 131, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 180, 131, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 230, 131, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 290, 131, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(120, 350, 131, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(120, 410, 131, 20))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(30, 460, 81, 61))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(160, 480, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(30, 560, 81, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(self.tab)
        self.lineEdit_10.setGeometry(QtCore.QRect(30, 630, 81, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 560, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 630, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(300, 30, 54, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(300, 250, 54, 12))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tableWidget_2 = QtGui.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(300, 41, 921, 191))
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_3 = QtGui.QTableWidget(self.tab)
        self.tableWidget_3.setGeometry(QtCore.QRect(300, 270, 931, 381))
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.tab)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(120, 30, 131, 22))
        self.dateTimeEdit_2.setObjectName(_fromUtf8("dateTimeEdit_2"))
        self.label_35 = QtGui.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(30, 380, 221, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(30, 70, 54, 12))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 120, 54, 12))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 170, 54, 12))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 230, 54, 12))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(30, 290, 61, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(30, 340, 61, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(30, 400, 71, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 470, 54, 12))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(120, 70, 141, 20))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(120, 120, 141, 20))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(120, 170, 141, 20))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(120, 230, 141, 20))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.lineEdit_15 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(120, 290, 141, 20))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_16 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(120, 340, 141, 20))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.lineEdit_17 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(120, 400, 141, 20))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.lineEdit_18 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(120, 470, 141, 20))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.dateTimeEdit_3 = QtGui.QDateTimeEdit(self.tab_2)
        self.dateTimeEdit_3.setGeometry(QtCore.QRect(120, 30, 141, 22))
        self.dateTimeEdit_3.setObjectName(_fromUtf8("dateTimeEdit_3"))
        self.tableWidget_4 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_4.setGeometry(QtCore.QRect(30, 500, 81, 61))
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(30, 580, 81, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_19 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_19.setGeometry(QtCore.QRect(30, 630, 81, 20))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 520, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 580, 75, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(170, 630, 75, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(310, 30, 54, 12))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(310, 230, 54, 12))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.tableWidget_5 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_5.setGeometry(QtCore.QRect(310, 40, 911, 181))
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.tableWidget_6 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_6.setGeometry(QtCore.QRect(310, 250, 911, 401))
        self.tableWidget_6.setObjectName(_fromUtf8("tableWidget_6"))
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(30, 440, 191, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.dateTimeEdit_4 = QtGui.QDateTimeEdit(self.tab_3)
        self.dateTimeEdit_4.setGeometry(QtCore.QRect(120, 30, 131, 22))
        self.dateTimeEdit_4.setObjectName(_fromUtf8("dateTimeEdit_4"))
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(30, 80, 54, 12))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(30, 120, 54, 12))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(30, 160, 54, 12))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(30, 210, 54, 12))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(30, 260, 61, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(30, 320, 61, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(30, 370, 71, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(30, 440, 54, 12))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(300, 30, 54, 12))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(300, 240, 54, 12))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.lineEdit_20 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_20.setGeometry(QtCore.QRect(120, 80, 131, 20))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.lineEdit_21 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_21.setGeometry(QtCore.QRect(120, 120, 131, 20))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.lineEdit_22 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_22.setGeometry(QtCore.QRect(120, 160, 131, 20))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.lineEdit_23 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_23.setGeometry(QtCore.QRect(120, 210, 131, 20))
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.lineEdit_24 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_24.setGeometry(QtCore.QRect(120, 260, 131, 20))
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.lineEdit_25 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_25.setGeometry(QtCore.QRect(120, 320, 131, 20))
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.lineEdit_26 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_26.setGeometry(QtCore.QRect(120, 370, 131, 20))
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.lineEdit_27 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_27.setGeometry(QtCore.QRect(120, 430, 131, 20))
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.label_34 = QtGui.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(30, 400, 161, 20))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.tableWidget_7 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_7.setGeometry(QtCore.QRect(30, 470, 81, 61))
        self.tableWidget_7.setObjectName(_fromUtf8("tableWidget_7"))
        self.tableWidget_7.setColumnCount(0)
        self.tableWidget_7.setRowCount(0)
        self.tableWidget_8 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_8.setGeometry(QtCore.QRect(300, 40, 921, 192))
        self.tableWidget_8.setObjectName(_fromUtf8("tableWidget_8"))
        self.tableWidget_8.setColumnCount(0)
        self.tableWidget_8.setRowCount(0)
        self.tableWidget_9 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_9.setGeometry(QtCore.QRect(300, 260, 921, 401))
        self.tableWidget_9.setObjectName(_fromUtf8("tableWidget_9"))
        self.tableWidget_9.setColumnCount(0)
        self.tableWidget_9.setRowCount(0)
        self.lineEdit_28 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_28.setGeometry(QtCore.QRect(30, 560, 91, 20))
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.lineEdit_29 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_29.setGeometry(QtCore.QRect(30, 620, 91, 20))
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 480, 75, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(170, 560, 75, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(170, 620, 75, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "迁移工具", None))
        self.tabWidget.setToolTip(_translate("Form", "<html><head/><body><p>ZJ</p></body></html>", None))
        self.label.setText(_translate("Form", "迁移时间", None))
        self.label_2.setText(_translate("Form", "原VIP", None))
        self.label_3.setText(_translate("Form", "目标VIP", None))
        self.label_4.setText(_translate("Form", "原VIPWeb", None))
        self.label_5.setText(_translate("Form", "目标VIPWeb", None))
        self.label_6.setText(_translate("Form", "原Servadd", None))
        self.label_7.setText(_translate("Form", "目标Servadd", None))
        self.label_8.setText(_translate("Form", "差异", None))
        self.pushButton.setText(_translate("Form", "插入", None))
        self.pushButton_2.setText(_translate("Form", "查询plan", None))
        self.pushButton_3.setText(_translate("Form", "查询edb", None))
        self.label_9.setText(_translate("Form", "MigPlan", None))
        self.label_10.setText(_translate("Form", "MigEDB", None))
        self.dateTimeEdit_2.setDisplayFormat(_translate("Form", "yyyy-M-d H:mm:ss", None))
        self.label_35.setText(_translate("Form", "整迁下框填0，差异迁填1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "整 机 迁 移", None))
        self.label_11.setText(_translate("Form", "迁移时间", None))
        self.label_12.setText(_translate("Form", "主账号", None))
        self.label_13.setText(_translate("Form", "原VIP", None))
        self.label_14.setText(_translate("Form", "目标VIP", None))
        self.label_15.setText(_translate("Form", "原VIPWeb", None))
        self.label_16.setText(_translate("Form", "目标VIPWeb", None))
        self.label_17.setText(_translate("Form", "原Servadd", None))
        self.label_18.setText(_translate("Form", "目标Servadd", None))
        self.label_19.setText(_translate("Form", "差异", None))
        self.dateTimeEdit_3.setDisplayFormat(_translate("Form", "yyyy-M-d H:mm:ss", None))
        self.pushButton_4.setText(_translate("Form", "插入", None))
        self.pushButton_5.setText(_translate("Form", "查询plan", None))
        self.pushButton_6.setText(_translate("Form", "查询edb", None))
        self.label_20.setText(_translate("Form", "MigPlan", None))
        self.label_21.setText(_translate("Form", "MigEDB", None))
        self.label_33.setText(_translate("Form", "全备迁下框填0，差异迁填1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "普 通 迁 移", None))
        self.dateTimeEdit_4.setDisplayFormat(_translate("Form", "yyyy-M-d H:mm:ss", None))
        self.label_22.setText(_translate("Form", "迁移时间", None))
        self.label_23.setText(_translate("Form", "主账号", None))
        self.label_24.setText(_translate("Form", "原VIP", None))
        self.label_25.setText(_translate("Form", "目标VIP", None))
        self.label_26.setText(_translate("Form", "原VIPWeb", None))
        self.label_27.setText(_translate("Form", "目标VIPWeb", None))
        self.label_28.setText(_translate("Form", "原Servadd", None))
        self.label_29.setText(_translate("Form", "目标Servadd", None))
        self.label_30.setText(_translate("Form", "差异", None))
        self.label_31.setText(_translate("Form", "MigPlan", None))
        self.label_32.setText(_translate("Form", "MigEDB", None))
        self.label_34.setText(_translate("Form", "全备迁下框填0，差异迁填1", None))
        self.pushButton_7.setText(_translate("Form", "插入", None))
        self.pushButton_8.setText(_translate("Form", "查询plan", None))
        self.pushButton_9.setText(_translate("Form", "查询edb", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "升 级 独 享", None))

